server:
  port: 9004
spring:
  application:
    name: cloud-article
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.2:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: mysql

  redis:
    host: 192.168.2.2
    port: 6379

