server:
  port: 9999
spring:
  application:
    name: cloud-base

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.2:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: root

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
  rabbitmq:
    host: 192.168.2.2
mybatis:
  type-aliases-package: com.jbb.base.entity
  mapper-locations: classpath*:mapping/**/*Mapper.xml
logging:
  level:
    com.jbb.base.dao.mybatis: debug
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.2:6868/eureka
  instance:
    prefer-ip-address: true
test: 1