server:
  port: 9005
spring:
  application:
    name: cloud-gathering
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.2:3306/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 192.168.2.2
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.2:6868/eureka
  instance:
    prefer-ip-address: true