server:
  port: 10001
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jbbzbq/springcloud.git
          search-paths: /config
          default-label: master