server:
  port: 9002
spring:
  application:
    name: cloud-recruit
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.2:3306/tensquare_recruit?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: mysql

eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.2:6868/eureka
  instance:
    prefer-ip-address: true